version: "3"
services:
  app:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
      - MYSQL_HOST=hostname
    ports: 
      - "5000:5000"
    restart: always
    depends_on:
      - db
  db:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=***
      - MYSQL_DATABASE=dbname
      - MYSQL_USER=dbuser
    volumes:
      - "data:/var/lib/mysql"
volumes:
  data: